### ISSUE TITLE
TS03 - Separar Login - Desenvolvedor

### ISSUE THREAD

**Issue by marceloabk** [fga-gpp-mds/2017.2-Classificacao-de-Risco-Pediatrico#35]
Eu, como desenvolvedor, desejo separar o login dos usuários para que eles possam realizar apenas as suas funções.

**Critérios de Aceitação:**
- [x] O sistema deve identificar o tipo de usuário após o seu login.
- [x] Alterar o template de login removendo as abas.
- [x] O usuário deve ser redirecionado para a página correspondente ao seu tipo.
- [ ] Realizar testes.

**Comment by MarcoRLK** [comment]
Critérios de Aceitação:
- [ ]  Teste

**Comment by MarcoRLK** [comment]
Critérios de Aceitação:

- [ ] O sistema deve identificar o tipo de usuário após o seu login.

- [ ] Alterar o template de login removendo as abas.

- [ ] O usuário deve ser redirecionado para a página correspondente ao seu tipo.

- [ ] Realizar testes.
