### ISSUE TITLE
US02 - Excluir Usuário - Administrador

### ISSUE THREAD

**Issue by ThiagosLima** [fga-gpp-mds/2017.2-Classificacao-de-Risco-Pediatrico#36]
Eu, como administrador, quero remover qualquer usuário do sistema para que possa manter o cadastro atualizado.

**Critérios de Aceitação:**

- [x] Implementar exibição de uma lista de funcionários.
- [x] Implementar um sistema de busca pelo ID de usuário do funcionário.
- [x] O funcionário excluído não deve mais existir no banco de dados.
- [x] Realizar testes unitários.

**Comment by MarcoRLK** [comment]
Critérios de Aceitação:

- [ ] Implementar exibição de uma lista de funcionários.
- [ ] Implementar um sistema de busca pelo ID de usuário do funcionário.
- [ ] O funcionário excluído não deve mais existir no banco de dados.
- [ ] Realizar testes unitários.
