### ISSUE TITLE
US03 - Cadastro de Paciente - Recepcionista ou Atendente ou Administrador

### ISSUE THREAD

**Issue by MarthaDs** [fga-gpp-mds/2017.2-Classificacao-de-Risco-Pediatrico#39]
Eu, como recepcionista ou atendente ou administrador, desejo cadastrar as informações dos pacientes para tê-los registrados no sistema.

**Comment by MarcoRLK** [comment]
Critérios de Aceitação:

- [ ] Implementar templates para o cadastro de um paciente.
- [ ] O paciente cadastrado deve ser registrado no banco de dados.
- [ ] Garantir que Recepcionista, Atendente e Administrador podem cadastrar um paciente.
- [ ] Realizar testes unitários.
