### ISSUE TITLE
US04 - Editar Cadastro de Paciente - Recepcionista ou atendente ou administrador

### ISSUE THREAD

**Issue by MarthaDs** [fga-gpp-mds/2017.2-Classificacao-de-Risco-Pediatrico#43]
Eu, como recepcionista ou atendente ou administrador, desejo editar cadastros de pacientes, para  poder atualizar as suas informações. 

**Critérios de Aceitação:**

- [x] Implementar a exibição de uma lista de pacientes.
- [x] Implementar um sistema de busca pelo CPF do paciente.
- [x] Implementar templates para a edição.
- [x] Os dados alterados devem ser atualizados no banco de dados.
- [x] Realizar testes unitários.

**Comment by MarcoRLK** [comment]
Critérios de Aceitação:

- [ ] Implementar a exibição de uma lista de pacientes.
- [ ] Implementar um sistema de busca pelo CPF do paciente.
- [ ] Implementar templates para a edição.
- [ ] Os dados alterados devem ser atualizados no banco de dados.
- [ ] Realizar testes unitários.
