### ISSUE TITLE
US01 - Cancelar cadastro - Administrador ou Recepcionista ou Atendente

### ISSUE THREAD

**Issue by marceloabk** [fga-gpp-mds/2017.2-Classificacao-de-Risco-Pediatrico#71]
Eu, como administrador ou recepcionista ou atendente, desejo cancelar um cadastro para interromper o processo em sua execução.

**Comment by MarcoRLK** [comment]
Critérios de Aceitação:

- [ ] Implementar um botão capaz de sair de qualquer tela de cadastro.
- [ ] Realizar testes.
