### ISSUE TITLE
TS01 - Teste Models - Desenvolvedor

### ISSUE THREAD

**Issue by marceloabk** [fga-gpp-mds/2017.2-Classificacao-de-Risco-Pediatrico#73]

**Comment by MarcoRLK** [comment]
Eu, como desenvolvedor, desejo implementar os testes unitários das models para garantir seus métodos estão funcionando corretamente.

Critérios de aceitação:

 Alcançar pelo menos 90% de cobertura de testes no arquivo models.py.

**Comment by MarcoRLK** [comment]
Eu, como desenvolvedor, desejo implementar os testes unitários das models para garantir seus métodos estão funcionando corretamente.

Critérios de aceitação:

- [ ] Alcançar pelo menos 90% de cobertura de testes no arquivo models.py.
