### ISSUE TITLE
TS09 - Filtrar acesso as páginas pelo login

### ISSUE THREAD

**Issue by ThiagosLima** [fga-gpp-mds/2017.2-Classificacao-de-Risco-Pediatrico#82]
Eu, como desenvolvedor, desejo realizar autenticação das páginas para controlar os seus acessos.

- [x]  Qualquer página que deveria ser acessada por um usuário logado deve redirecionar para a home caso não tenha um usuário logado.

**Comment by victoralvesgomide** [comment]
Tivemos dificuldades com a parte dos testes e precisamos de ajuda para verificar se o usuário está logado ou instanciá-lo dentro do teste. Contudo, conseguimos verificar a autenticação do usuário na template.
