### ISSUE TITLE
TS07 - Refatorar navegação entre páginas

### ISSUE THREAD

**Issue by ThiagosLima** [fga-gpp-mds/2017.2-Classificacao-de-Risco-Pediatrico#87]
Eu, como desenvolvedor, desejo refatorar a navegação das páginas para melhorar a usabilidade da aplicação.

**Comment by MarthaDs** [comment]
- [ ] Todas as páginas devem possuir um link para página principal.

- [ ] Cada pagina deve ser linkada a pelo menos uma pagina.
